
package co.com.codesoftware.servicio.contabilidad;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContabilidadWS", targetNamespace = "http://contabilidad.servicio.codesoftware.com.co/", wsdlLocation = "http://localhost:8777/SIGEMCOWS/ContabilidadWS?wsdl")
public class ContabilidadWS_Service
    extends Service
{

    private final static URL CONTABILIDADWS_WSDL_LOCATION;
    private final static WebServiceException CONTABILIDADWS_EXCEPTION;
    private final static QName CONTABILIDADWS_QNAME = new QName("http://contabilidad.servicio.codesoftware.com.co/", "ContabilidadWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8777/SIGEMCOWS/ContabilidadWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTABILIDADWS_WSDL_LOCATION = url;
        CONTABILIDADWS_EXCEPTION = e;
    }

    public ContabilidadWS_Service() {
        super(__getWsdlLocation(), CONTABILIDADWS_QNAME);
    }

    public ContabilidadWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTABILIDADWS_QNAME, features);
    }

    public ContabilidadWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONTABILIDADWS_QNAME);
    }

    public ContabilidadWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTABILIDADWS_QNAME, features);
    }

    public ContabilidadWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContabilidadWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContabilidadWS
     */
    @WebEndpoint(name = "ContabilidadWSPort")
    public ContabilidadWS getContabilidadWSPort() {
        return super.getPort(new QName("http://contabilidad.servicio.codesoftware.com.co/", "ContabilidadWSPort"), ContabilidadWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContabilidadWS
     */
    @WebEndpoint(name = "ContabilidadWSPort")
    public ContabilidadWS getContabilidadWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://contabilidad.servicio.codesoftware.com.co/", "ContabilidadWSPort"), ContabilidadWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTABILIDADWS_EXCEPTION!= null) {
            throw CONTABILIDADWS_EXCEPTION;
        }
        return CONTABILIDADWS_WSDL_LOCATION;
    }

}
