
package co.com.codesoftware.server.productos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductosEndPoint", targetNamespace = "http://productos.server.codesoftware.com.co/", wsdlLocation = "http://localhost:8777/SIGEMCOWS/ProductosEndPoint?wsdl")
public class ProductosEndPoint_Service
    extends Service
{

    private final static URL PRODUCTOSENDPOINT_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOSENDPOINT_EXCEPTION;
    private final static QName PRODUCTOSENDPOINT_QNAME = new QName("http://productos.server.codesoftware.com.co/", "ProductosEndPoint");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8777/SIGEMCOWS/ProductosEndPoint?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOSENDPOINT_WSDL_LOCATION = url;
        PRODUCTOSENDPOINT_EXCEPTION = e;
    }

    public ProductosEndPoint_Service() {
        super(__getWsdlLocation(), PRODUCTOSENDPOINT_QNAME);
    }

    public ProductosEndPoint_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOSENDPOINT_QNAME, features);
    }

    public ProductosEndPoint_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOSENDPOINT_QNAME);
    }

    public ProductosEndPoint_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOSENDPOINT_QNAME, features);
    }

    public ProductosEndPoint_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductosEndPoint_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductosEndPoint
     */
    @WebEndpoint(name = "ProductosEndPointPort")
    public ProductosEndPoint getProductosEndPointPort() {
        return super.getPort(new QName("http://productos.server.codesoftware.com.co/", "ProductosEndPointPort"), ProductosEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductosEndPoint
     */
    @WebEndpoint(name = "ProductosEndPointPort")
    public ProductosEndPoint getProductosEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://productos.server.codesoftware.com.co/", "ProductosEndPointPort"), ProductosEndPoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOSENDPOINT_EXCEPTION!= null) {
            throw PRODUCTOSENDPOINT_EXCEPTION;
        }
        return PRODUCTOSENDPOINT_WSDL_LOCATION;
    }

}
