
package co.com.codesoftware.server.nsigemco;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdministrationEndPoint", targetNamespace = "http://nsigemco.server.codesoftware.com.co/", wsdlLocation = "http://localhost:8777/SIGEMCOWS/AdministrationEndPoint?wsdl")
public class AdministrationEndPoint_Service
    extends Service
{

    private final static URL ADMINISTRATIONENDPOINT_WSDL_LOCATION;
    private final static WebServiceException ADMINISTRATIONENDPOINT_EXCEPTION;
    private final static QName ADMINISTRATIONENDPOINT_QNAME = new QName("http://nsigemco.server.codesoftware.com.co/", "AdministrationEndPoint");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8777/SIGEMCOWS/AdministrationEndPoint?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINISTRATIONENDPOINT_WSDL_LOCATION = url;
        ADMINISTRATIONENDPOINT_EXCEPTION = e;
    }

    public AdministrationEndPoint_Service() {
        super(__getWsdlLocation(), ADMINISTRATIONENDPOINT_QNAME);
    }

    public AdministrationEndPoint_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINISTRATIONENDPOINT_QNAME, features);
    }

    public AdministrationEndPoint_Service(URL wsdlLocation) {
        super(wsdlLocation, ADMINISTRATIONENDPOINT_QNAME);
    }

    public AdministrationEndPoint_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINISTRATIONENDPOINT_QNAME, features);
    }

    public AdministrationEndPoint_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationEndPoint_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdministrationEndPoint
     */
    @WebEndpoint(name = "AdministrationEndPointPort")
    public AdministrationEndPoint getAdministrationEndPointPort() {
        return super.getPort(new QName("http://nsigemco.server.codesoftware.com.co/", "AdministrationEndPointPort"), AdministrationEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrationEndPoint
     */
    @WebEndpoint(name = "AdministrationEndPointPort")
    public AdministrationEndPoint getAdministrationEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nsigemco.server.codesoftware.com.co/", "AdministrationEndPointPort"), AdministrationEndPoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINISTRATIONENDPOINT_EXCEPTION!= null) {
            throw ADMINISTRATIONENDPOINT_EXCEPTION;
        }
        return ADMINISTRATIONENDPOINT_WSDL_LOCATION;
    }

}
